services:
  - type: web
    name: collab-board-backend
    env: docker
    rootDir: backend

    envVars:
      - key: MONGODB_URL
        sync: false

      - key: REDIS_URL
        sync: false

      - key: JWT_SECRET_KEY
        generateValue: true

      - key: CORS_ORIGINS_RAW
        sync: false
