services:
  - type: web
    name: collab-board-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false
